station:
    privileges: lab
    station_all:
    - LTT
    - FL #(前左):0x1E
    - FR #(前右):0x50
    - RL #(后左):0x1F
    - RML #(后中左):0x51
    - RMR #(后中右):0x52
    - RR #(后右):0x53
    station_name: FL
    station_no: FL-3000
    log_folder: D:\TestLog
    log_server: 10.90.104.85
    log_server_username: eero
    log_server_password: eero
    fix_flag: false
    fix_com_port: COM3
    fix_com_baudRate: 115200
    GPIB_address: 9
    testcase: PLIN-BLF.xlsx
    fail_continue: false
    mes_shop_floor: 10.90.104.126:8080
    mes_result: 10.90.104.104:8080
    rs_url: http://luxshare:bento@10.90.104.16:8100/api/1/
    csv_column: csv_column.txt
    continue_fail_limit: 3
    loop_interval: 0
    loop_count: 0
    setTimeZone:
dut:
    prompt: root@OpenWrt:/#
    dut_ip: 192.168.1.101
    dut_com_port: COM7
    dut_com_baudRate: 115200
    ssh_port: 22
    ssh_username: root
    ssh_password: root
    dut_models:
    - cento
    - gateway
    - leaf
    - firefly
    dut_regex:
        cento: '[A-Z0-9]+$'
        gateway: '[A-Z0-9]+$'
        leaf: '[A-Z0-9]+$'
        firefly: '[A-Z0-9]+$'
    data_api:
        cento: cento_data_api_client.py
        gateway: anytown_data_api_client.py
        leaf: anytown_data_api_client.py
        firefly: firefly_data_api_client.py
    sn_len: 16
    qsdk_ver: 029
    test_mode: production
    debug_skip:
    - SetIpaddrEnv
    - GetIpaddrEnv
    - CheckEeroTest
    - Checkroute
    - CheckEeroABA
    - SetDHCP
