station:
    privileges: lab
    station_all:
    - Sample
    - LTT1
    - M4
    - M6
    - SX5GEV
    - SX5GEV_EOL
    - ReadVer_M4
    - ReadVer_SX5GEV
    - ALE_M4
    - ALE_M6
    - ALE_SX5GEV
    station_name: SX5GEV
    station_no: SX5GEV
    log_folder: D:\TestLog
    log_server: 10.90.104.85
    log_server_username: eero
    log_server_password: eero
    fix_com_port: COM3
    fix_com_baudRate: 115200
    GPIB_address: 9
    testcase: PLIN-BLF.xlsx
    mes_shop_floor: 10.90.104.126:8080
    mes_result: 10.90.104.104:8080
    rs_url: http://xxxxxx/api/1/
    csv_column: csv_column.txt
    continue_fail_limit: 3
    LoopInterval: 0
    LoopMaximum: -1 # <=0:无线循环
    LoopNumPassed: -1 # -1
    setTimeZone:
    fix_flag: false
    fail_continue: false
    auto_scan: false
dut:
    prompt: root@OpenWrt:/#
    dut_ip: 192.168.1.101
    dut_com_port: COM7
    dut_com_baudRate: 115200
    ssh_port: 22
    ssh_username: root
    ssh_password: root
    dut_models:
    - cento212
    dut_regex:
        cento212: '[A-Z0-9]+$'
    data_api:
        cento212: cento_data_api_client.py
    sn_len: 16
    qsdk_ver: 029
    test_mode: production
    debug_skip:
    - SetIpaddrEnv
    - SetDHCP
    mysql_connect:
        host: 127.0.0.1
        port: 3307
        database: lebo
        charset: utf8
        user: root
        passwd: root
BLF:
    ReqDelay: 10
    RespDelay: 10
    ReadTxCount: 1000
    MRtoMRDelay: 0.1
    SchedulePeriod: 20
RUNIN:
    row: 5 # group No,<=10
    col: 4 # <=8
LTT:
    row: 5 # group No,<=10
    col: 4 # <=8
    channel: 1
    Volt: 13.5
    Curr: 12
