station:
    privileges: lab
    stationAll:
    - CalOBC7CANID
    stationName: CalOBC7CANID
    stationNo: CalOBC7CANID
    logFolder: D:\TestLog
    logServer: 10.90.104.85
    logServerUser: eero
    logServerPwd: eero
    fixComPort: COM3
    fixComBaudRate: 115200
    GPIBPort: 9
    testcase: PLIN-BLF.xlsx
    mesShopFloor: 10.90.104.126:8080
    mesServer: 10.90.104.104:8080
    rs_url: http://xxxxxx/api/1/
    continueFailLimit: 3
    LoopInterval: 0
    LoopMaximum: -1 # <=0:无线循环
    LoopNumPassed: -1 # -1
    setTimeZone:
    fixFlag: false
    failContinue: false
    autoScan: false
dut:
    prompt: root@OpenWrt:/#
    dutIP: 192.168.1.101
    dutComPort: COM7
    dutComBaudRate: 115200
    sshUser: root
    sshPwd: root
    dutModels:
    - cento212
    dutSNRegex:
        cento212: '[A-Z0-9]+$'
    dataAPI:
        cento212: cento_data_api_client.py
    snLen: 16
    sdkVer: 029
    testMode: production
    debugSkip:
    - SetIpaddrEnv
    - SetDHCP
    mysqlInfo:
        host: 127.0.0.1
        port: 3307
        database: lebo
        charset: utf8
        user: root
        passwd: root
BLF:
    ReqDelay: 10
    RespDelay: 10
    ReadTxCount: 1000
    MRtoMRDelay: 0.1
    SchedulePeriod: 20
RUNIN:
    IsRUNIN: false
    row: 10 # group No,<=10
    col: 8 # <=8
LTT:
    row: 5 # group No,<=10
    col: 4 # <=8
    channel: 1
    Volt: 13.5
    Curr: 12
Updates:
    FTPServer: 10.177.4.201
    FTPUser: user
    FTPPwd: pwd
Vector:
    interface: vector
    channel: 1
    bitrate: 500
    app_name: python-can
PCAN:
    interface: pcan
    channel: PCAN_USBBUS1
    bitrate: 500
CANalystII:
    interface: canalystii
    channel: 1
    bitrate: 500

