station:
    privileges: lab
    station_all:
    - FL #(前左):0x1E
    - FR #(前右):0x50
    - RL #(后左):0x1F
    - RML #(后中左):0x51
    - RMR #(后中右):0x52
    - RR #(后右):0x53
    station_name: FL
    station_no: FL-3000
    log_folder: D:\TestLog
    log_server: 10.90.104.85
    log_server_username: eero
    log_server_password: eero
    fix_com_port: COM3
    fix_com_baudRate: 115200
    GPIB_address: 9
    testcase: PLIN-BLF.xlsx
    mes_shop_floor: 10.90.104.126:8080
    mes_result: 10.90.104.104:8080
    rs_url: http://xxxxxx/api/1/
    csv_column: csv_column.txt
    continue_fail_limit: 3
    loop_interval: 0
    loop_count: 0
    setTimeZone:
    fix_flag: false
    fail_continue: false
dut:
    prompt: root@OpenWrt:/#
    dut_ip: 192.168.1.101
    dut_com_port: COM7
    dut_com_baudRate: 115200
    ssh_port: 22
    ssh_username: root
    ssh_password: root
    dut_models:
    - xxx1
    dut_regex:
        cento212: '[A-Z0-9]+$'
    data_api:
        cento212: cento_data_api_client.py
    sn_len: 16
    qsdk_ver: 029
    test_mode: production
    debug_skip:
    -
    -
BLF:
    ReqDelay: 10
    RespDelay: 10

