!!python/object:__main__.Configs
station: !!python/object:__main__.StationConf
    privileges: lab
    station_all:
    - Sample
    - FL_M6
    - LTT5
    station_name: FL_M6
    station_no: FL_M6
    log_folder: D:\TestLog
    log_server: 10.90.104.85
    log_server_username: eero
    log_server_password: eero
    fix_com_port: COM3
    fix_com_baudRate: 115200
    GPIB_address: 9
    testcase: PLIN-BLF.xlsx
    mes_shop_floor: 10.90.104.126:8080
    mes_result: 10.90.104.104:8080
    rs_url: http://xxxxxx/api/1/
    csv_column: csv_column.txt
    continue_fail_limit: 3
    loop_interval: 0
    loop_count: 0
    setTimeZone: null
    fix_flag: false
    fail_continue: false
    auto_scan: false
dut: !!python/object:__main__.DutConf
    prompt: root@OpenWrt:/#
    dut_ip: 192.168.1.101
    dut_com_port: COM7
    dut_com_baudRate: 115200
    ssh_port: 22
    ssh_username: root
    ssh_password: root
    dut_models:
    - cento212
    dut_regex:
        cento212: '[A-Z0-9]+$'
    data_api:
        cento212: cento_data_api_client.py
    sn_len: 16
    qsdk_ver: 029
    test_mode: production
    debug_skip:
    - SetIpaddrEnv
    - SetDHCP
BLF: !!python/object:__main__.DutConf
    ReqDelay: 10
    RespDelay: 10
    readTxCount: 1000
    MRtoMRDelay: 0.1
RUNIN: !!python/object:__main__.DutConf
    row: 5
    col: 4
    channel: 1
