station:
    privileges: labs
    station_all:
    - LTT
    - FL_M4 #(前左):0x1E
    - FR_M4 #(前右):0x50
    - RL_M4 #(后左):0x1F
    - RML_M4 #(后中左):0x51
    - RMR_M4 #(后中右):0x52
    - RR_M4 #(后右):0x53
    - FL_SX5GEV #(前左):0x1E
    - FR_SX5GEV #(前右):0x50
    - RL_SX5GEV #(后左):0x1F
    - RM_SX5GEV #(后中):0x51
    - RR_SX5GEV #(后右):0x53
    - FLB_SX5GEV #(前左保杠):0x52
    - FRB_SX5GEV #(前右保杠):0x54
    station_name: FL_M4
    station_no: FL_M4
    log_folder: D:\TestLog
    log_server: 10.90.104.85
    log_server_username: eero
    log_server_password: eero
    fix_com_port: COM3
    fix_com_baudRate: 115200
    GPIB_address: 9
    testcase: PLIN-BLF.xlsx
    mes_shop_floor: 10.90.104.126:8080
    mes_result: 10.90.104.104:8080
    rs_url: http://xxxxxx/api/1/
    csv_column: csv_column.txt
    continue_fail_limit: 3
    loop_interval: 0
    loop_count: 0
    setTimeZone:
    fix_flag: false
    fail_continue: false
dut:
    prompt: root@OpenWrt:/#
    dut_ip: 192.168.1.101
    dut_com_port: COM7
    dut_com_baudRate: 115200
    ssh_port: 22
    ssh_username: root
    ssh_password: root
    dut_models:
    - xxx1
    dut_regex:
        cento212: '[A-Z0-9]+$'
    data_api:
        cento212: cento_data_api_client.py
    sn_len: 16
    qsdk_ver: 029
    test_mode: production
    debug_skip:
    - SetIpaddrEnv
    - SetDHCP
BLF:
    ReqDelay: 10
    RespDelay: 10

