--- #0 logger配置信息
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(levelname)-8s - %(filename)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: $log_file
    encoding: utf8
  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: simple
    filename: $critical_log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: $errors_log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  root:
    level: DEBUG
    handlers: [ console ]
  testlog:
    level: DEBUG
    handlers: [ console,file_handler,critical_file_handler,error_file_handler ]
    propagate: no

