# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_peak.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeakGui(object):
    def setupUi(self, PeakGui):
        PeakGui.setObjectName("PeakGui")
        PeakGui.setWindowModality(QtCore.Qt.NonModal)
        PeakGui.resize(521, 236)
        self.verticalLayout = QtWidgets.QVBoxLayout(PeakGui)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PeakGui)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setContentsMargins(20, 20, 30, 20)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.hardwareCbx = QtWidgets.QComboBox(self.tab)
        self.hardwareCbx.setObjectName("hardwareCbx")
        self.gridLayout.addWidget(self.hardwareCbx, 0, 1, 1, 2)
        self.connectBt = QtWidgets.QPushButton(self.tab)
        self.connectBt.setObjectName("connectBt")
        self.gridLayout.addWidget(self.connectBt, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.modeCbx = QtWidgets.QComboBox(self.tab)
        self.modeCbx.setObjectName("modeCbx")
        self.gridLayout.addWidget(self.modeCbx, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.baudrateCbx = QtWidgets.QComboBox(self.tab)
        self.baudrateCbx.setObjectName("baudrateCbx")
        self.gridLayout.addWidget(self.baudrateCbx, 1, 1, 1, 2)
        self.refreshBt = QtWidgets.QPushButton(self.tab)
        self.refreshBt.setObjectName("refreshBt")
        self.gridLayout.addWidget(self.refreshBt, 0, 3, 1, 1)
        self.releaseBt = QtWidgets.QPushButton(self.tab)
        self.releaseBt.setObjectName("releaseBt")
        self.gridLayout.addWidget(self.releaseBt, 3, 3, 1, 1)
        self.identifyBt = QtWidgets.QPushButton(self.tab)
        self.identifyBt.setObjectName("identifyBt")
        self.gridLayout.addWidget(self.identifyBt, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(PeakGui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PeakGui)

    def retranslateUi(self, PeakGui):
        _translate = QtCore.QCoreApplication.translate
        PeakGui.setWindowTitle(_translate("PeakGui", "PEAK"))
        self.connectBt.setText(_translate("PeakGui", "Connect"))
        self.label_3.setText(_translate("PeakGui", "Mode:"))
        self.label.setText(_translate("PeakGui", "Hardware:"))
        self.label_2.setText(_translate("PeakGui", "Baudrate:"))
        self.refreshBt.setText(_translate("PeakGui", "Refresh"))
        self.releaseBt.setText(_translate("PeakGui", "Release"))
        self.identifyBt.setText(_translate("PeakGui", "Identify"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PeakGui", "PEAK-LIN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PeakGui", "PEAK-CAN"))
