script_str = """
[
    {
        "myWind": null,
        "logger": null,
        "name": "InitPLIN",
        "_index": 0,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "InitPLIN",
                "_StepName": "InitPlin",
                "_Keyword": "PLINInitConnectELV",
                "_Retry": 0,
                "_Timeout": 2,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "SuspendDiagSchedule",
                "_Keyword": "SuspendDiagSchedule",
                "_Retry": 1,
                "_Timeout": 1,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "PositionLightOn",
        "_index": 1,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "PositionLightOn",
                "_StepName": "Position32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "08 80 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "Position33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "00 00 02 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 5,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "PositionLightOff",
        "_index": 2,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "PositionLightOff",
                "_StepName": "Position32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 00 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "Position33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "00 00 02 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 1,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Locking",
        "_index": 3,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "Locking",
                "_StepName": "locking32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 00 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "locking33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "00 08 02 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 5,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Unlocking",
        "_index": 4,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "Unlocking",
                "_StepName": "unlocking32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 00 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "unlocking33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "00 00 02 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 10,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Parking",
        "_index": 5,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "Parking",
                "_StepName": "parking32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 80 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "parking33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "00 00 02 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 20,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Charger",
        "_index": 6,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "Charger",
                "_StepName": "charger32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 00 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "charger33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "F4 01 02 01 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 10,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Reverse",
        "_index": 7,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 3,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "Reverse",
                "_StepName": "reverse32",
                "_Keyword": "PLINGetMsg32",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "32",
                "_CmdOrParam": "00 80 00 00 00 00 00 C8",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "reverse33",
                "_Keyword": "PLINGetMsg33",
                "_Retry": 0,
                "_Timeout": 0,
                "ID": "33",
                "_CmdOrParam": "F4 01 32 00 00 00 00 00",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "waiting",
                "_Keyword": "WaitingALE",
                "_Retry": 0,
                "_Timeout": 10,
                "ID": "",
                "_CmdOrParam": "",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    }
]
"""


def get_script_str():
    return globals()['script_str']
