script_str = """
[
    {
        "myWind": null,
        "logger": null,
        "name": "InitPLIN",
        "_index": 0,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "InitPLIN",
                "StepName": "InitPlin",
                "_Keyword": "PLINInitConnectELV",
                "Retry": 0,
                "Timeout": 2,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "SuspendDiagSchedule",
                "_Keyword": "SuspendDiagSchedule",
                "Retry": 1,
                "Timeout": 1,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Car search",
        "_index": 1,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Car search",
                "StepName": "unlocking32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "05 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "WelcomeOn",
        "_index": 2,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "WelcomeOn",
                "StepName": "welcomeOn32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "09 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Lock",
        "_index": 3,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Lock",
                "StepName": "welcomeOff32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "11 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Power on",
        "_index": 4,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Power on",
                "StepName": "autoparkClose32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "21 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Power Down",
        "_index": 5,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Power Down",
                "StepName": "locking32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "41 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Parking",
        "_index": 6,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Parking",
                "StepName": "parking32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "81 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Autopark",
        "_index": 7,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Autopark",
                "StepName": "autopark32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "01 FD FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Charge",
        "_index": 8,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Charge",
                "StepName": "autoparkClose32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "33",
                "CmdOrParam": "84 42 45 FF FF FF F0 FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 10,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "Turn off",
        "_index": 9,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "Turn off",
                "StepName": "locking32",
                "_Keyword": "PLINGetMsg32",
                "Retry": 0,
                "Timeout": 0,
                "ID": "34",
                "CmdOrParam": "01 FC FF FF FF FF FF FF",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "waiting",
                "_Keyword": "WaitingALE",
                "Retry": 0,
                "Timeout": 1,
                "ID": "",
                "CmdOrParam": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    }
]
"""


def get_script_str():
    return globals()['script_str']
