script_str = """
[
    {
        "myWind": null,
        "logger": null,
        "name": "ReadAllVersion",
        "_index": 0,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 13,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "ReadAllVersion",
                "_StepName": "InitPlin",
                "_Keyword": "PLINInitConnect",
                "_Retry": 0,
                "_Timeout": 2,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "",
                "_NAD": "",
                "_PCI_LEN": "",
                "_CmdOrParam": "",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "1E",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "FL_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "1E",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 3,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "50",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 4,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "FR_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "50",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 5,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "1F",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 6,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "RL_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "1F",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 7,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "51",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 8,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "RML_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "51",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 9,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "52",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 10,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "RMR_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "52",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 11,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "ECUReset",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "",
                "_SubStr2": "",
                "ID": "3C",
                "_NAD": "53",
                "_PCI_LEN": "02",
                "_CmdOrParam": "11 01",
                "_CheckStr1": "",
                "_ByPF": "",
                "_Json": "",
                "NeverUsed": null,
                "SuiteName": ""
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 12,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "_SuiteName": "",
                "_StepName": "RR_M4",
                "_Keyword": "PLINSingleFrame",
                "_Retry": 1,
                "_Timeout": 1,
                "_SubStr1": "62",
                "_SubStr2": "FF",
                "ID": "3C",
                "_NAD": "53",
                "_PCI_LEN": "03",
                "_CmdOrParam": "22 F1 55",
                "_CheckStr1": "",
                "_ByPF": "P",
                "_Json": "Y",
                "NeverUsed": null,
                "SuiteName": ""
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    }
]
"""


def get_script_str():
    return globals()['script_str']
