script_str = """
[
    {
        "myWind": null,
        "logger": null,
        "name": "PoweSupplySet",
        "_index": 0,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 10,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "PoweSupplySet",
                "StepName": "OpenPS",
                "_Keyword": "NiVisaOpenInstr",
                "ErrorCode": "2.1.1: NiVisaOpen",
                "Retry": 1,
                "Timeout": 0,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "USB0::0x0957::0x8407::US21D4120S::INSTR",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_SetVOLTProtect",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "VOLT:PROT:LEV 30",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 2,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_SetCURRProtect",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "CURR:PROT:STAT 10",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 3,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_SetVOLT",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "VOLT 13.5",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "Y",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 4,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_SetCURR",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "CURR 12",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 5,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_SetOutputOn",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "OUTP ON",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 6,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "OperationCompleteCheck",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "*OPC?",
                "Param1": "",
                "ExpectStr": "1",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 7,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_MeasureVOLT",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "Meas:VOLT?",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 8,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_MeasureCURR",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "Meas:CURR?",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 9,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "PS_ERR",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "Syst:err?",
                "Param1": "",
                "ExpectStr": "No error",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "WA580-Open",
        "_index": 1,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "WA580-Open",
                "StepName": "SerialPortOpen",
                "_Keyword": "SerialPortOpen",
                "ErrorCode": "3.1.0: Device.Serial.Timeout",
                "Retry": 0,
                "Timeout": 3,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "COM2",
                "Param1": "",
                "ExpectStr": "9600",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "ROUT Slot,Channel,On",
                "ErrorCode": "3.1.0: Device.Serial.Timeout",
                "Retry": 1,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "ROUT 1,<CellNo>,1",
                "Param1": "",
                "ExpectStr": "OK",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "WA580-Close",
        "_index": 2,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "WA580-Close",
                "StepName": "SerialPortOpen",
                "_Keyword": "SerialPortOpen",
                "ErrorCode": "3.1.0: Device.Serial.Timeout",
                "Retry": 0,
                "Timeout": 3,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "COM2",
                "Param1": "",
                "ExpectStr": "9600",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "ROUT Slot,Channel,Off",
                "ErrorCode": "3.1.0: Device.Serial.Timeout",
                "Retry": 1,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "ROUT 1,<CellNo>,0",
                "Param1": "",
                "ExpectStr": "OK",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "SampleCycleSet",
        "_index": 3,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 1,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "SampleCycleSet",
                "StepName": "StartFor",
                "_Keyword": "StartFor",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "FOR(3)",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "DAQ-temp",
        "_index": 4,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "DAQ-temp",
                "StepName": "OpenDAQ970A-temp",
                "_Keyword": "NiVisaOpenInstr",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "USB0::0x2A8D::0x5001::MY58009299::INSTR",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "GetDAQTemp",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 3,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "MEAS:TEMP:TCouple? K,(@101:120)",
                "Param1": "<CellNo>",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "Y",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "DAQ-Resistor",
        "_index": 5,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 2,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "DAQ-Resistor",
                "StepName": "OpenDAQ970A-Resistor",
                "_Keyword": "NiVisaOpenInstr",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 1,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "USB0::0x2A8D::0x5001::MY58009297::INSTR",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            },
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 1,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "",
                "StepName": "GetDAQResistor",
                "_Keyword": "NiVisaCmd",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 3,
                "For": "",
                "SubStr1": "",
                "SubStr2": "\\n",
                "CmdOrParam": "MEASure:FRES? 100,(@10<CellNo>)",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "Y",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "DAQ-Cur",
        "_index": 6,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 1,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "DAQ-Cur",
                "StepName": "GetCurDev1",
                "_Keyword": "NiDAQmxCur",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 10,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "Dev1/ai{<CellNo>-1}",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "-10",
                "USL": "10",
                "Unit": "A",
                "_Json": "Y",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "DAQ-Volt",
        "_index": 7,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 1,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "DAQ-Volt",
                "StepName": "GetVoltDev2",
                "_Keyword": "NiDAQmxVolt",
                "ErrorCode": "7.6: Linux.KernelStartTimeout",
                "Retry": 0,
                "Timeout": 10,
                "For": "",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "Dev2/ai{<CellNo>-1}",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "-20",
                "USL": "30",
                "Unit": "V",
                "_Json": "Y",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    },
    {
        "myWind": null,
        "logger": null,
        "name": "SampleIntervalSet",
        "_index": 8,
        "isTest": true,
        "suiteResult": true,
        "isTestFinished": false,
        "totalNumber": 1,
        "suiteVar": "",
        "steps": [
            {
                "myWind": null,
                "logger": null,
                "breakpoint": false,
                "suiteIndex": 0,
                "_index": 0,
                "testValue": null,
                "start_time": null,
                "finish_time": null,
                "start_time_json": null,
                "error_code": "",
                "error_details": "",
                "status": "exception",
                "elapsedTime": 0,
                "_isTest": true,
                "suiteVar": "",
                "SuiteName": "SampleIntervalSet",
                "StepName": "Interval",
                "_Keyword": "Waiting",
                "ErrorCode": "0.1.1: ThreadSleep",
                "Retry": 0,
                "Timeout": 10,
                "For": "ENDFOR",
                "SubStr1": "",
                "SubStr2": "",
                "CmdOrParam": "",
                "Param1": "",
                "ExpectStr": "",
                "LSL": "",
                "USL": "",
                "Unit": "",
                "_Json": "",
                "NeverUsed": null
            }
        ],
        "start_time": null,
        "finish_time": null,
        "error_code": "",
        "phase_details": "",
        "elapsedTime": null
    }
]
"""


def get_script_str():
    return globals()['script_str']
